sudo: false
language: ruby
rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3
cache:
  bundler: true
before_install:
  - gem update --system
  - gem install bundler

branches:
  only:
    - master
script:
  - bundle exec rubocop
  - bundle exec rubycritic --no-browser -s 90 -f console
